export type {
  ArchicatAliasConfig,
  ArchicatAppContract,
  ArchicatAppDependencies,
  ArchicatAppDependency,
  ArchicatAppInput,
  ArchicatConfig,
  ArchicatConfigInput,
  ArchicatDefinitionRootConfig,
  ArchicatLibraryApiDependencies,
  ArchicatLibraryApiDependency,
  ArchicatLibraryContract,
  ArchicatLibraryImplDependencies,
  ArchicatLibraryImplDependency,
  ArchicatLibraryInput,
  ArchicatModuleApiDependencies,
  ArchicatModuleApiDependency,
  ArchicatModuleContract,
  ArchicatModuleImplDependencies,
  ArchicatModuleImplDependency,
  ArchicatModuleInput,
  ArchicatPrefixConfig,
  ArchicatSurfaceConfig,
  ArchicatSurfaceContract,
  ArchicatSurfaceInput,
} from './configs/index';
export { defineApp, defineArchicatConfig, defineLibrary, defineModule } from './configs/index';
