export type {
  AliasConfig,
  AppsConfigInput,
  ArchicatAppContract,
  ArchicatAppDependencies,
  ArchicatAppDependency,
  ArchicatAppInput,
  ArchicatConfig,
  ArchicatConfigInput,
  ArchicatLibraryApiDependencies,
  ArchicatLibraryApiDependency,
  ArchicatLibraryContract,
  ArchicatLibraryImplDependencies,
  ArchicatLibraryImplDependency,
  ArchicatLibraryInput,
  ArchicatModuleApiDependencies,
  ArchicatModuleApiDependency,
  ArchicatModuleContract,
  ArchicatModuleImplDependencies,
  ArchicatModuleImplDependency,
  ArchicatModuleInput,
  ArchicatSurfaceConfig,
  ArchicatSurfaceContract,
  ArchicatSurfaceInput,
  LibrariesConfigInput,
  ModulesConfigInput,
  TsConfigInput,
  TypeScriptConfigInput,
} from './configuration';
export { defineApp, defineArchicatConfig, defineLibrary, defineModule } from './configuration';
